name: Golang Build Check

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Make All
        run: |
          ./package.sh

      - name: List release files
        run: |
          ls ./release
        id: list_files
          
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: Release Files
          path: ${{ steps.list_files.outputs.stdout }}
