name: Golang Build Check

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Make All
        run: |
          ./package.sh
          
      - name: List Files
        id: list_files
        run: |
          echo "::set-output name=files::$(ls ./packages/*)"

      - name: Upload Files
        run: |
          for file in ${{ steps.list_files.outputs.files }}; do
            name=$(basename "$file")
            echo "Uploading $name..."
            echo "::set-output name=upload_step::$file"
            uses: actions/upload-artifact@v2
            with:
              name: $name
              path: $file
          done
