name: Golang Build Check

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Make All
        run: |
          ./package.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./release
