name: Go Check 

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Frpc
      run: go build -v ./cmd/frpc/main.go
      
    - name: Build Frps
      run: go build -v ./cmd/frps/main.go

    - name: Test Frpc
      run: go test -v ./cmd/frpc/main.go
      
    - name: Test Frps
      run: go test -v ./cmd/frps/main.go
